//7: Express JS: 
//7.1: Defination: Express.js is a minimal and flexible web application framework for Node.js
// It provides a robust set of features for building single page, multi page, and hybrid web applications 
// Express.Js simplifies server side coding by providing a layer of fundamental web application features. 

//7.2 Need of Express Js: 
// 1) It simplifies Server Creation: Helps in quickly setting up and running a web server
// 2) Routing Management: Provides a powerful routing mechanism to Handle URLs and HTTP methods effectively.
// 3) Middleware Support: Allows the use of middleware to Handle Requests, Response, and many middle operations, making code modular and maintainable
// 4) API devlopment: Fecilitates easy and efficient creaation of RESTful API's
// 5) Community and Plugins: Has a large ecosystem with numerous plugins nd extensions, accelearting devlopment time.

//7.3: Installing Express.JS: 